# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20160405_0929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='interaction',
        ),
        migrations.AddField(
            model_name='profile',
            name='birthday',
            field=models.DateField(null=True, verbose_name='birthday'),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.PositiveIntegerField(null=True, verbose_name='gender'),
        ),
        migrations.AddField(
            model_name='profile',
            name='home_address',
            field=models.CharField(max_length=200, null=True, verbose_name='home_address'),
        ),
        migrations.AddField(
            model_name='profile',
            name='office_address',
            field=models.CharField(max_length=200, null=True, verbose_name='office_address'),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(max_length=12, null=True, verbose_name='phone_number'),
        ),
        migrations.AddField(
            model_name='profile',
            name='reviews',
            field=models.IntegerField(default=0, verbose_name='reviews'),
        ),
    ]
